export const TIMELINE_POSTS_REQUEST='TIMELINE_POSTS_REQUEST';
export const TIMELINE_POSTS_SUCCESS='TIMELINE_POSTS_SUCCESS';
export const TIMELINE_POSTS_FAIL='TIMELINE_POSTS_FAIL';

export const PROFILE_POSTS_REQUEST='PROFILE_POSTS_REQUEST';
export const PROFILE_POSTS_SUCCESS='PROFILE_POSTS_REQUEST';
export const PROFILE_POSTS_FAIL='PROFILE_POSTS_REQUEST';

export const LIKEUNLIKE_POST_REQUEST='LIKEUNLIKE_POST_REQUEST';
export const LIKEUNLIKE_POST_SUCCESS='LIKEUNLIKE_POST_SUCCESS';
export const LIKEUNLIKE_POST_FAIL='LIKEUNLIKE_POST_FAIL';